data(iris)
data(iris)
str(iris)
colnames(iris)
head(iris)
tail(iris)
rownames(iris)
#View(iris)
mean(iris$Sepal.Length)
median(iris$Sepal.Length)
max(iris$Sepal.Length)
min(iris$Sepal.Length)
sum(iris$Sepal.Length)
sd(iris$Sepal.Length)
var(iris$Sepal.Length)

hist(iris$Sepal.Length)
plot(iris$Sepal.Length)
vec<-({iris$Sepal.Width})
print(vec)

vec1<-seq({iris$})